#!/usr/bin/with-contenv sh

set -x
mkdir -p /var/www/magento/app/etc
if [[ -z "${MAGENTO_CACHE_HOST}" ]]; then
	cp /var/magento-config/local.xml /var/www/magento/app/etc/local.xml
else 
	cp /var/magento-config/local-redis.xml /var/www/magento/app/etc/local.xml
fi

chown magento:users /var/www/magento/app/etc/local.xml

sed -i "s/{{MAGENTO_DB_NAME}}/${MAGENTO_DB_NAME}/g" /var/www/magento/app/etc/local.xml
sed -i "s/{{MAGENTO_DB_HOST}}/${MAGENTO_DB_HOST}/g" /var/www/magento/app/etc/local.xml
sed -i "s/{{MAGENTO_DB_USER}}/${MAGENTO_DB_USER}/g" /var/www/magento/app/etc/local.xml
sed -i "s/{{MAGENTO_DB_PASSWORD}}/${MAGENTO_DB_PASSWORD}/g" /var/www/magento/app/etc/local.xml

sed -i "s/{{MAGENTO_SESSION_HOST}}/${MAGENTO_SESSION_HOST}/g" /var/www/magento/app/etc/local.xml
sed -i "s/{{MAGENTO_SESSION_PORT}}/${MAGENTO_SESSION_PORT}/g" /var/www/magento/app/etc/local.xml
sed -i "s/{{MAGENTO_SESSION_DATABASE}}/${MAGENTO_SESSION_DATABASE}/g" /var/www/magento/app/etc/local.xml

sed -i "s/{{MAGENTO_CACHE_HOST}}/${MAGENTO_CACHE_HOST}/g" /var/www/magento/app/etc/local.xml
sed -i "s/{{MAGENTO_CACHE_PORT}}/${MAGENTO_CACHE_PORT}/g" /var/www/magento/app/etc/local.xml
sed -i "s/{{MAGENTO_CACHE_DATABASE}}/${MAGENTO_CACHE_DATABASE}/g" /var/www/magento/app/etc/local.xml

sed -i "s/{{MAGENTO_WEBCACHE_HOST}}/${MAGENTO_WEBCACHE_HOST}/g" /var/www/magento/app/etc/local.xml

sed -i "s/{{MAGENTO_ADMIN_URL}}/${MAGENTO_ADMIN_URL:-admin}/g" /var/www/magento/app/etc/local.xml
sed -i "s/{{MAGENTO_CRYPT}}/${MAGENTO_CRYPT}/g" /var/www/magento/app/etc/local.xml

sed -i "s/{{MAGENTO_CRYPT}}/${MAGENTO_CRYPT}/g" /var/www/magento/app/etc/local.xml

